### ISSUE TITLE
unable to compile

### ISSUE THREAD

**Issue by 500ghz** [ifh101/CSC535#5]
The file greyWhiteTransitions.jpg is not allowing me to compile because it has a capital W and T
This is the error I get:
Error:Error: 'W' is not a valid file-based resource name character: File-based resource names must contain only lowercase a-z, 0-9, or underscore
:app:mergeDebugResources FAILED
Error:Execution failed for task ':app:mergeDebugResources'.
/Users/omarabid/StudioProjects/5/Scanner/app/src/main/res/drawable/greyWhiteTransition.jpg: Error: 'W' is not a valid file-based resource name character: File-based resource names must contain only lowercase a-z, 0-9, or underscore

**Comment by IdrisHanafi** [comment]
just change the background image resolution to a smaller one and remove
capital letters
